class Color:
    """ ANSI color codes """
    BLACK = "\033[0;30m"
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    BROWN = "\033[0;33m"
    BLUE = "\033[0;34m"
    PURPLE = "\033[0;35m"
    CYAN = "\033[0;36m"
    LIGHT_GRAY = "\033[0;37m"
    DARK_GRAY = "\033[1;30m"
    LIGHT_RED = "\033[1;31m"
    LIGHT_GREEN = "\033[1;32m"
    YELLOW = "\033[1;33m"
    LIGHT_BLUE = "\033[1;34m"
    LIGHT_PURPLE = "\033[1;35m"
    LIGHT_CYAN = "\033[1;36m"
    LIGHT_WHITE = "\033[1;37m"
    BOLD = "\033[1m"
    FAINT = "\033[2m"
    ITALIC = "\033[3m"
    UNDERLINE = "\033[4m"
    BLINK = "\033[5m"
    NEGATIVE = "\033[7m"
    CROSSED = "\033[9m"
    END = "\033[0m"


class ANSI(str):
    black        = lambda self: f"{Color.BLACK}{self}{Color.END}"
    red          = lambda self: f"{Color.RED}{self}{Color.END}"
    green        = lambda self: f"{Color.GREEN}{self}{Color.END}"
    brown        = lambda self: f"{Color.BROWN}{self}{Color.END}"
    blue         = lambda self: f"{Color.BLUE}{self}{Color.END}"
    purple       = lambda self: f"{Color.PURPLE}{self}{Color.END}"
    cyan         = lambda self: f"{Color.CYAN}{self}{Color.END}"
    light_gray   = lambda self: f"{Color.LIGHT_GRAY}{self}{Color.END}"
    dark_gray    = lambda self: f"{Color.DARK_GRAY}{self}{Color.END}"
    light_red    = lambda self: f"{Color.LIGHT_RED}{self}{Color.END}"
    light_green  = lambda self: f"{Color.LIGHT_GREEN}{self}{Color.END}"
    yellow       = lambda self: f"{Color.YELLOW}{self}{Color.END}"
    light_blue   = lambda self: f"{Color.LIGHT_BLUE}{self}{Color.END}"
    light_purple = lambda self: f"{Color.LIGHT_PURPLE}{self}{Color.END}"
    light_cyan   = lambda self: f"{Color.LIGHT_CYAN}{self}{Color.END}"
    light_white  = lambda self: f"{Color.LIGHT_WHITE}{self}{Color.END}"
    bold         = lambda self: f"{Color.BOLD}{self}{Color.END}"
    faint        = lambda self: f"{Color.FAINT}{self}{Color.END}"
    italic       = lambda self: f"{Color.ITALIC}{self}{Color.END}"
    underline    = lambda self: f"{Color.UNDERLINE}{self}{Color.END}"
    blink        = lambda self: f"{Color.BLINK}{self}{Color.END}"
    negative     = lambda self: f"{Color.NEGATIVE}{self}{Color.END}"
    crossed      = lambda self: f"{Color.CROSSED}{self}{Color.END}"